apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    release: {{ .Release.Name }}
    chart: '{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}'
type: Opaque
data:
  OCI_TENANCY: {{ .Values.oci.tenancy | required "oci.tenancy must be set" | b64enc  }}
  OCI_USER: {{ .Values.oci.user | required "oci.user must be set" | b64enc  }}
  OCI_FINGERPRINT: {{ .Values.oci.fingerprint | required "oci.fingerprint must be set" | b64enc  }}
  OCI_PRIVATE_KEY: {{ .Values.oci.privateKey | required "oci.privateKey must be set" | b64enc }}